### ISSUE TITLE
#pre-title is not printing the correct copy for the movies 

### ISSUE THREAD

**Issue by AshaLaura** [youthradio/Netflix-Remix#11]
When I clicked Action Male Black, I was shown Black Panther but the #pre-title said "A Action Movie with A Asian Male Lead is..." 

I replicated this issue, and I got the Jumanji movie but it said A Action Movie with A Black Female Lead is...

**Comment by shagia** [comment]
Fixed! Refer to #12 which is now merged to the master and viewable.
